name: CI
on:  
  push:    
    branches:      
      - main
jobs:  
  validate-html:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout code        
        uses: actions/checkout@v3      
        
      - name: Validate HTML        
        run: |
          htmlhint index.html
